//! import-font — Extract BIZ UDPGothic (Morisawa, SIL OFL) outlines for a
//! target character set and emit `src/glyph/font_outlines_data.rs` (Rust
//! const, no_std-compatible).
//!
//! Outlines are flattened to polylines (Bezier subdivided) and stored in
//! em-normalized coordinates (units_per_em → 1.0). Each glyph carries its
//! horizontal advance width in em units. The rasterizer in
//! `glyph::font_render` consumes this data.
//!
//! Two tables are emitted:
//!   - FONT_OUTLINES_REGULAR — from BIZUDPGothic-Regular.ttf
//!   - FONT_OUTLINES_BOLD    — from BIZUDPGothic-Bold.ttf
//!
//! Usage:
//!   cargo run --release
//!
//! License: outline DATA is derived from BIZ UDPGothic (SIL OFL 1.1).
//! See fonts/OFL.txt for terms.
//!
//! Author: Moroya Sakamoto

use std::path::PathBuf;
use ttf_parser::{Face, OutlineBuilder};

const QUAD_SUBDIVS: usize = 8;
const CUBIC_SUBDIVS: usize = 12;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut chars: Vec<char> = std::env::args()
        .skip(1)
        .filter_map(|s| s.chars().next())
        .collect();
    if chars.is_empty() {
        chars = default_charset();
    }
    chars.sort();
    chars.dedup();

    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let regular_path = manifest.join("fonts/BIZUDPGothic-Regular.ttf");
    let bold_path = manifest.join("fonts/BIZUDPGothic-Bold.ttf");
    let regular_data = std::fs::read(&regular_path)?;
    let bold_data = std::fs::read(&bold_path)?;
    let regular_face = Face::parse(&regular_data, 0)?;
    let bold_face = Face::parse(&bold_data, 0)?;
    eprintln!(
        "Loaded {} ({} glyphs, units_per_em={})",
        regular_path.display(),
        regular_face.number_of_glyphs(),
        regular_face.units_per_em()
    );
    eprintln!(
        "Loaded {} ({} glyphs, units_per_em={})",
        bold_path.display(),
        bold_face.number_of_glyphs(),
        bold_face.units_per_em()
    );

    let out_path = manifest.join("../../src/glyph/font_outlines_data.rs");
    let mut out = String::new();
    out.push_str("// Auto-generated by tools/import-font. Do not edit by hand.\n");
    out.push_str("//\n");
    out.push_str("// Glyph outlines from BIZ UDPGothic (Morisawa, SIL OFL 1.1).\n");
    out.push_str("// See tools/import-font/fonts/OFL.txt for license terms.\n");
    out.push_str("//\n");
    out.push_str("// Coordinates are normalized to em units: units_per_em -> 1.0.\n");
    out.push_str("// Origin: baseline (y=0), pen start (x=0).\n");
    out.push_str("// Third tuple element: horizontal advance in em units.\n");
    out.push_str("\n");

    emit_table(&mut out, "FONT_OUTLINES_REGULAR", &regular_face, &chars);
    out.push('\n');
    emit_table(&mut out, "FONT_OUTLINES_BOLD", &bold_face, &chars);

    std::fs::write(&out_path, &out)?;
    eprintln!("Wrote {}", out_path.display());
    Ok(())
}

fn emit_table(out: &mut String, name: &str, face: &Face<'_>, chars: &[char]) {
    use core::fmt::Write;
    let upem = face.units_per_em() as f32;
    let inv_upem = 1.0 / upem;
    writeln!(out, "/// (codepoint, contour-list, advance-em).").unwrap();
    writeln!(out, "/// Sorted ascending for binary search.").unwrap();
    writeln!(
        out,
        "pub static {}: &[(char, &[&[(f32, f32)]], f32)] = &[",
        name
    )
    .unwrap();

    let mut emitted = 0usize;
    let mut skipped = 0usize;
    let mut advance_only = 0usize;
    for ch in chars {
        let Some(glyph_id) = face.glyph_index(*ch) else {
            skipped += 1;
            continue;
        };
        let advance_em =
            face.glyph_hor_advance(glyph_id).unwrap_or(0) as f32 * inv_upem;

        let mut builder = PathBuilder::new();
        let has_outline = face.outline_glyph(glyph_id, &mut builder).is_some();
        if !has_outline || builder.contours.is_empty() {
            // Space and other non-drawing glyphs: emit advance-only entry.
            writeln!(
                out,
                "    ('\\u{{{:04X}}}', &[], {:.4}),",
                *ch as u32, advance_em
            )
            .unwrap();
            advance_only += 1;
            emitted += 1;
            continue;
        }

        let normalized = normalise_em(&builder.contours, inv_upem);
        emit_char(out, *ch, &normalized, advance_em);
        emitted += 1;
    }
    writeln!(out, "];").unwrap();
    eprintln!(
        "  {}: {} chars emitted ({} advance-only), {} skipped",
        name, emitted, advance_only, skipped
    );
}

fn default_charset() -> Vec<char> {
    let ascii: String = (0x20u32..=0x7E).filter_map(char::from_u32).collect();

    let extoria_kanji = "一上世並中了予事人今仕他付代以件任企会体作供価保信値倫備先公共内処出分列制前創力功加効動務化匿取受可号合名向品問善回圧在地型報変外多大失奨始子存学守完定実客容察対専工己幅広序度引張当役後従志応思性情想意感憶成戦戻所手技折択担拡持指挑捗推提援撃支改攻敗散数文料新明易時更最有期未本来果検業概構様模次正残比気汎活測無率現理生用由界略番異発的目相真知研確社私種究立端答築精累組結絡続総締縮績義習考者能自荷融行術表要見規視観言計託記設証評試話詳認語読談論識護負貫資質起超軸軽較込返述送透通速連進運達適選避部重金録長門閉開間際難電面順題類験高魅";

    let radicals = "丨丶丿乙亅二亠儿入八冂冖冫几凵刀勹匕匚匸卜卩厂厶又囗士夂夊夕宀寸尢尸屮巛巾干幺廴廾弋弓彐彡彳戈戶支攴斗斤方无曰欠止歹殳毋比毛氏气爪父爻爿片牙牛玄瓜瓦甘生用田疋癶皮皿矛矢示禸禾穴竹米缶网羊羽老而耒耳聿臣自至臼舌舛舟艮色虍血襾角谷豆豕豸赤走身辛辰辵邑酉釆里隶隹雨青非革韋韭音頁風飛食首香骨高髟鬥鬯鬲鬼魚鳥鹵鹿麥麻黃黍黑黹黽鼎鼓鼠鼻齊齒龍龜龠";

    let extra_kanji = "株式会社加速機械学習認証感情長期記憶並列実行制作支援基盤先端技術変革鳥山孫悟空仲";

    // Extoria の 4 領域看板 (T1 で使う)
    let domain_kanji = "領域難他受担当我々挑戦解決導入問題観測実装最適";

    let hiragana: String = (0x3041u32..=0x3096).filter_map(char::from_u32).collect();
    let katakana: String = (0x30A1u32..=0x30FC).filter_map(char::from_u32).collect();

    // 全角記号 + long-dash + いくつかの punctuation
    let jp_punct = "、。「」『』・…—−ー(){}〈〉《》【】〔〕（）？©→≠·";

    // v2 の messages/*.json + pages/*.json で参照される追加 kanji
    let missing_kanji = "依全強描景画索背製統像独御覚映";

    let mut all = String::new();
    all.push_str(&ascii);
    all.push_str(extoria_kanji);
    all.push_str(extra_kanji);
    all.push_str(domain_kanji);
    all.push_str(missing_kanji);
    all.push_str(radicals);
    all.push_str(&hiragana);
    all.push_str(&katakana);
    all.push_str(jp_punct);
    all.chars().collect()
}

fn normalise_em(contours: &[Vec<(f32, f32)>], inv_upem: f32) -> Vec<Vec<(f32, f32)>> {
    let mut out = Vec::with_capacity(contours.len());
    for c in contours {
        let mut nc = Vec::with_capacity(c.len());
        for &(x, y) in c {
            // TTF y-up preserved. x in [0, ~advance_em], y in [-descent_em, ascent_em].
            nc.push((x * inv_upem, y * inv_upem));
        }
        out.push(nc);
    }
    out
}

fn emit_char(out: &mut String, ch: char, contours: &[Vec<(f32, f32)>], advance: f32) {
    use core::fmt::Write;
    write!(out, "    ('\\u{{{:04X}}}', &[", ch as u32).unwrap();
    for (i, c) in contours.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str("&[");
        for (j, (x, y)) in c.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            write!(out, "({:.4},{:.4})", x, y).unwrap();
        }
        out.push_str("]");
    }
    writeln!(out, "], {:.4}),", advance).unwrap();
}

/// Build glyph outlines into a list of closed polylines.
struct PathBuilder {
    contours: Vec<Vec<(f32, f32)>>,
    cur: Vec<(f32, f32)>,
    last: (f32, f32),
}

impl PathBuilder {
    fn new() -> Self {
        Self {
            contours: Vec::new(),
            cur: Vec::new(),
            last: (0.0, 0.0),
        }
    }

    fn flush(&mut self) {
        if !self.cur.is_empty() {
            let c = std::mem::take(&mut self.cur);
            self.contours.push(c);
        }
    }
}

impl OutlineBuilder for PathBuilder {
    fn move_to(&mut self, x: f32, y: f32) {
        self.flush();
        self.cur.push((x, y));
        self.last = (x, y);
    }
    fn line_to(&mut self, x: f32, y: f32) {
        self.cur.push((x, y));
        self.last = (x, y);
    }
    fn quad_to(&mut self, x1: f32, y1: f32, x: f32, y: f32) {
        for i in 1..=QUAD_SUBDIVS {
            let t = i as f32 / QUAD_SUBDIVS as f32;
            let u = 1.0 - t;
            let px = u * u * self.last.0 + 2.0 * u * t * x1 + t * t * x;
            let py = u * u * self.last.1 + 2.0 * u * t * y1 + t * t * y;
            self.cur.push((px, py));
        }
        self.last = (x, y);
    }
    fn curve_to(&mut self, x1: f32, y1: f32, x2: f32, y2: f32, x: f32, y: f32) {
        for i in 1..=CUBIC_SUBDIVS {
            let t = i as f32 / CUBIC_SUBDIVS as f32;
            let u = 1.0 - t;
            let px = u * u * u * self.last.0
                + 3.0 * u * u * t * x1
                + 3.0 * u * t * t * x2
                + t * t * t * x;
            let py = u * u * u * self.last.1
                + 3.0 * u * u * t * y1
                + 3.0 * u * t * t * y2
                + t * t * t * y;
            self.cur.push((px, py));
        }
        self.last = (x, y);
    }
    fn close(&mut self) {
        if let Some(&first) = self.cur.first() {
            self.cur.push(first);
        }
        self.flush();
    }
}
