//! import-noto — Extract Noto Sans JP outlines for a target character set and
//! emit `src/glyph/noto_outlines_data.rs` (Rust const, no_std-compatible).
//!
//! Outlines are flattened to polylines (Bezier subdivided), normalised into
//! the unit square `[0, 1] × [0, 1]` with the glyph centred. The rasterizer
//! in `glyph::noto_render` consumes this data.
//!
//! Not used at runtime — produces a const file that `ALICE-Font` compiles in.
//!
//! Usage:
//!   cargo run --release        # imports the default char list
//!   cargo run --release -- 株 式  # imports only the listed chars
//!
//! License: outline DATA is derived from Noto Sans JP (SIL OFL).
//! See LICENSES/NotoSansJP-OFL.txt for terms.
//!
//! Author: Moroya Sakamoto

use std::path::PathBuf;
use ttf_parser::{Face, OutlineBuilder};

const QUAD_SUBDIVS: usize = 8;
const CUBIC_SUBDIVS: usize = 12;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut chars: Vec<char> = std::env::args()
        .skip(1)
        .filter_map(|s| s.chars().next())
        .collect();

    if chars.is_empty() {
        // Default set: extoria-website 267 kanji + key radicals + kana.
        chars = default_charset();
    }
    chars.sort();
    chars.dedup();

    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let font_path = manifest.join("../render-ref/data/NotoSansJP-Regular.ttf");
    let font_data = std::fs::read(&font_path)?;
    let face = Face::parse(&font_data, 0)?;
    eprintln!("Loaded font {} ({} glyphs)", font_path.display(), face.number_of_glyphs());

    // Output path: src/glyph/noto_outlines_data.rs
    let out_path = manifest.join("../../src/glyph/noto_outlines_data.rs");
    let mut out = String::new();
    out.push_str("// Auto-generated by tools/import-noto. Do not edit by hand.\n");
    out.push_str("//\n");
    out.push_str("// Outline polylines for CJK characters, sourced from Noto Sans JP (SIL OFL).\n");
    out.push_str("// Coordinates are normalised into [0, 1] x [0, 1]. Each character has one or\n");
    out.push_str("// more contours; each contour is a closed polyline.\n");
    out.push_str("\n");
    out.push_str("/// (codepoint, contour-list) entries. Sorted ascending for binary search.\n");
    out.push_str("/// Each contour is a slice of `(f32, f32)` points; consecutive points form\n");
    out.push_str("/// edges; the last point equals the first to close the contour.\n");
    out.push_str("pub static NOTO_OUTLINES: &[(char, &[&[(f32, f32)]])] = &[\n");

    let mut emitted = 0usize;
    let mut skipped = 0usize;
    for ch in &chars {
        let Some(glyph_id) = face.glyph_index(*ch) else {
            skipped += 1;
            continue;
        };
        let mut builder = PathBuilder::new();
        if face.outline_glyph(glyph_id, &mut builder).is_none() {
            skipped += 1;
            continue;
        }
        if builder.contours.is_empty() {
            skipped += 1;
            continue;
        }
        let bbox = builder.bbox().unwrap();
        let normalised = normalise_contours(&builder.contours, bbox);
        emit_char(&mut out, *ch, &normalised);
        emitted += 1;
    }
    out.push_str("];\n");

    std::fs::write(&out_path, &out)?;
    eprintln!("Wrote {} ({} chars, {} skipped)", out_path.display(), emitted, skipped);
    Ok(())
}

fn default_charset() -> Vec<char> {
    // extoria-website kanji + 214 Kangxi radicals + hiragana + katakana.
    let extoria_kanji = "一上世並中了予事人今仕他付代以件任企会体作供価保信値倫備先公共内処出分列制前創力功加効動務化匿取受可号合名向品問善回圧在地型報変外多大失奨始子存学守完定実客容察対専工己幅広序度引張当役後従志応思性情想意感憶成戦戻所手技折択担拡持指挑捗推提援撃支改攻敗散数文料新明易時更最有期未本来果検業概構様模次正残比気汎活測無率現理生用由界略番異発的目相真知研確社私種究立端答築精累組結絡続総締縮績義習考者能自荷融行術表要見規視観言計託記設証評試話詳認語読談論識護負貫資質起超軸軽較込返述送透通速連進運達適選避部重金録長門閉開間際難電面順題類験高魅";

    let radicals = "丨丶丿乙亅二亠儿入八冂冖冫几凵刀勹匕匚匸卜卩厂厶又囗士夂夊夕宀寸尢尸屮巛巾干幺廴廾弋弓彐彡彳戈戶支攴斗斤方无曰欠止歹殳毋比毛氏气爪父爻爿片牙牛玄瓜瓦甘生用田疋癶皮皿矛矢示禸禾穴竹米缶网羊羽老而耒耳聿臣自至臼舌舛舟艮色虍血襾角谷豆豕豸赤走身辛辰辵邑酉釆里隶隹雨青非革韋韭音頁風飛食首香骨高髟鬥鬯鬲鬼魚鳥鹵鹿麥麻黃黍黑黹黽鼎鼓鼠鼻齊齒龍龜龠";

    // ヒーロー / 製品 / セクション見出しなど extoria-website-sdf-v2 の pages/*.json
    // で参照される追加の字を補完。
    let extra_kanji = "株式会社加速機械学習認証感情長期記憶並列実行制作支援基盤先端技術変革";

    let hiragana: String = (0x3041u32..=0x3096).filter_map(char::from_u32).collect();
    let katakana: String = (0x30A1u32..=0x30FC).filter_map(char::from_u32).collect();

    let mut all = String::new();
    all.push_str(extoria_kanji);
    all.push_str(extra_kanji);
    all.push_str(radicals);
    all.push_str(&hiragana);
    all.push_str(&katakana);
    all.chars().collect()
}

fn normalise_contours(
    contours: &[Vec<(f32, f32)>],
    bbox: (f32, f32, f32, f32),
) -> Vec<Vec<(f32, f32)>> {
    let (gx0, gy0, gx1, gy1) = bbox;
    let gw = gx1 - gx0;
    let gh = gy1 - gy0;
    let g_max = gw.max(gh);
    let scale = 1.0 / g_max;
    let ox = 0.5 - (gw * scale) * 0.5;
    let oy = 0.5 - (gh * scale) * 0.5;
    let mut out = Vec::with_capacity(contours.len());
    for c in contours {
        let mut nc = Vec::with_capacity(c.len());
        for &(x, y) in c {
            // ttf-parser y-up → ALICE-Font also y-up (baseline=0, top=h).
            // We normalize y so that y=0 is bottom of glyph world, y=1 is top.
            let nx = ox + (x - gx0) * scale;
            let ny = oy + (y - gy0) * scale;
            nc.push((nx, ny));
        }
        out.push(nc);
    }
    out
}

fn emit_char(out: &mut String, ch: char, contours: &[Vec<(f32, f32)>]) {
    use core::fmt::Write;
    write!(out, "    ('\\u{{{:04X}}}', &[", ch as u32).unwrap();
    for (i, c) in contours.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str("&[");
        for (j, (x, y)) in c.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            write!(out, "({:.4},{:.4})", x, y).unwrap();
        }
        out.push_str("]");
    }
    out.push_str("]),\n");
}

/// Build glyph outlines into a list of closed polylines.
struct PathBuilder {
    contours: Vec<Vec<(f32, f32)>>,
    cur: Vec<(f32, f32)>,
    last: (f32, f32),
}

impl PathBuilder {
    fn new() -> Self {
        Self { contours: Vec::new(), cur: Vec::new(), last: (0.0, 0.0) }
    }

    fn bbox(&self) -> Option<(f32, f32, f32, f32)> {
        let mut min = (f32::MAX, f32::MAX);
        let mut max = (f32::MIN, f32::MIN);
        let mut found = false;
        for c in &self.contours {
            for p in c {
                min.0 = min.0.min(p.0);
                min.1 = min.1.min(p.1);
                max.0 = max.0.max(p.0);
                max.1 = max.1.max(p.1);
                found = true;
            }
        }
        if found { Some((min.0, min.1, max.0, max.1)) } else { None }
    }

    fn flush(&mut self) {
        if !self.cur.is_empty() {
            let c = std::mem::take(&mut self.cur);
            self.contours.push(c);
        }
    }
}

impl OutlineBuilder for PathBuilder {
    fn move_to(&mut self, x: f32, y: f32) {
        self.flush();
        self.cur.push((x, y));
        self.last = (x, y);
    }
    fn line_to(&mut self, x: f32, y: f32) {
        self.cur.push((x, y));
        self.last = (x, y);
    }
    fn quad_to(&mut self, x1: f32, y1: f32, x: f32, y: f32) {
        for i in 1..=QUAD_SUBDIVS {
            let t = i as f32 / QUAD_SUBDIVS as f32;
            let u = 1.0 - t;
            let px = u * u * self.last.0 + 2.0 * u * t * x1 + t * t * x;
            let py = u * u * self.last.1 + 2.0 * u * t * y1 + t * t * y;
            self.cur.push((px, py));
        }
        self.last = (x, y);
    }
    fn curve_to(&mut self, x1: f32, y1: f32, x2: f32, y2: f32, x: f32, y: f32) {
        for i in 1..=CUBIC_SUBDIVS {
            let t = i as f32 / CUBIC_SUBDIVS as f32;
            let u = 1.0 - t;
            let px = u*u*u*self.last.0 + 3.0*u*u*t*x1 + 3.0*u*t*t*x2 + t*t*t*x;
            let py = u*u*u*self.last.1 + 3.0*u*u*t*y1 + 3.0*u*t*t*y2 + t*t*t*y;
            self.cur.push((px, py));
        }
        self.last = (x, y);
    }
    fn close(&mut self) {
        if let Some(&first) = self.cur.first() {
            self.cur.push(first);
        }
        self.flush();
    }
}
